// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccwvfrsdorekqatnhwti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjd3ZmcnNkb3Jla3FhdG5od3RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NDgwODcsImV4cCI6MjA1ODMyNDA4N30.f61_AhE185uTxtklXvi-dGjNygZ2ft_5VH9XdH2KYNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);